language: rust
matrix:
  include:
    - name: Windows Server + MSVC
      os: windows
      install:
        - choco install strawberryperl
        - choco install cmake
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install llvm --version 11.1.0
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - cargo build --release --workspace
        - ./target/release/laplace-eq-therm-server.exe
        - ./target/release/laplace-eq-therm-client.exe