language: rust
matrix:
  include:
    - name: Windows Server + MSVC
      os: windows
      install:
        - choco install strawberryperl
        - choco install cmake
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install llvm --version 11.1.0
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - cargo build --release --workspace
        - ./target/release/laplace-eq-therm-server.exe
        - ./target/release/laplace-eq-therm-client.exe
    - name: Ubuntu 18.04 LTS + GCC
      os: linux
      dist: bionic
      sudo: required
      install:
        - sudo apt-get install build-essential
        - sudo apt-get install pkg-config
        - sudo apt-get install libudev-dev
        - sudo apt-get install libssl-dev
        - sudo apt-get install libclang-8-dev
      script:
        - export BINDGEN_EXTRA_CLANG_ARGS=-std=c++17
        - cargo build --release --workspace
        - ./target/release/laplace-eq-therm-server
        - ./target/release/laplace-eq-therm-client
    - name: macOS Big Sur + Clang
      os: osx
      osx_image: xcode12.5
      script:
        - export BINDGEN_EXTRA_CLANG_ARGS=-std=c++17
        - cargo build --release --workspace
        - ./target/release/laplace-eq-therm-server
        - ./target/release/laplace-eq-therm-client